Trying environment

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,18 +1,28 @@
 #!/bin/bash
 
 #TODO: Find out why environment script does not take these into account
-export NPM_MIRROR=http://zuul.eurobank.efg.gr/nexus/repository/npm-group/
-export NO_PROXY=zuul.eurobank.efg.gr
-export DEV_MODE=true
-export REACT_APP_BASENAME=/
-export FORCE_COLOR=true
+#export NPM_MIRROR=http://zuul.eurobank.efg.gr/nexus/repository/npm-group/
+#export NO_PROXY=zuul.eurobank.efg.gr
+#export DEV_MODE=true
+#export REACT_APP_BASENAME=/
+#export FORCE_COLOR=true
+
+echo "HTTP_PROXY $HTTP_PROXY"
+echo "HTTPS_PROXY $HTTPS_PROXY"
+echo "http_proxy $http_proxy"
+echo "https_proxy $https_proxy"
+echo "NPM_MIRROR $NPM_MIRROR"
+echo "DEV_MODE $DEV_MODE"
+echo "REACT_APP_BASENAME $REACT_APP_BASENAME"
+echo "FORCE_COLOR $FORCE_COLOR"
+echo "NO_PROXY $NO_PROXY"
 
 # Prevent running assemble in builders different than official STI image.
-# The official nodejs:4-onbuild already run npm install and use different
+# The official nodejs:6-onbuild already run npm install and use different
 # application folder.
 [ -d "/usr/src/app" ] && exit 0
 
-#set -e
+set -e
 
 # FIXME: Linking of global modules is disabled for now as it causes npm failures
 #        under RHEL7
@@ -37,43 +47,30 @@ shopt -s dotglob
 echo "---> Installing application source ..."
 mv /tmp/src/* ./
 
-#if [ ! -z $HTTP_PROXY ]; then
-    #echo "---> Setting npm http proxy to" $(safeLogging $HTTP_PROXY)
-	#npm config set proxy $HTTP_PROXY
-#fi
+if [ ! -z $HTTP_PROXY ]; then
+    echo "---> Setting npm http proxy to" $(safeLogging $HTTP_PROXY)
+	npm config set proxy $HTTP_PROXY
+fi
 
-#if [ ! -z $http_proxy ]; then
-    #echo "---> Setting npm http proxy to" $(safeLogging $http_proxy)
-	#npm config set proxy $http_proxy
-#fi
+if [ ! -z $http_proxy ]; then
+    echo "---> Setting npm http proxy to" $(safeLogging $http_proxy)
+	npm config set proxy $http_proxy
+fi
 
-#if [ ! -z $HTTPS_PROXY ]; then
-    #echo "---> Setting npm https proxy to" $(safeLogging $HTTPS_PROXY)
-	#npm config set https-proxy $HTTPS_PROXY
-#fi
+if [ ! -z $HTTPS_PROXY ]; then
+    echo "---> Setting npm https proxy to" $(safeLogging $HTTPS_PROXY)
+	npm config set https-proxy $HTTPS_PROXY
+fi
 
-#if [ ! -z $https_proxy ]; then
-    #echo "---> Setting npm https proxy to" $(safeLogging $https_proxy)
-	#npm config set https-proxy $https_proxy
-#fi
+if [ ! -z $https_proxy ]; then
+    echo "---> Setting npm https proxy to" $(safeLogging $https_proxy)
+	npm config set https-proxy $https_proxy
+fi
 
 # Change the npm registry mirror if provided
 if [ -n "$NPM_MIRROR" ]; then
 	npm config set registry $NPM_MIRROR
 fi
-
-echo "REACT_APP_BASENAME"
-echo $REACT_APP_BASENAME
-echo "FORCE_COLOR" 
-echo $FORCE_COLOR
-echo "DEV_MODE"
-echo $DEV_MODE
-echo "NO_PROXY" 
-echo $NO_PROXY
-echo "NPM_MIRROR" 
-echo $NPM_MIRROR
-echo "STI_SCRIPTS_PATH" 
-echo $STI_SCRIPTS_PATH
 
 # Set the DEV_MODE to false by default.
 if [ -z "$DEV_MODE" ]; then
@@ -90,51 +87,27 @@ if [ -z "$NODE_ENV" ]; then
   fi
 fi
 
-#if [ "$NODE_ENV" != "production" ]; then
+echo "---> Installing all dependencies"
+NODE_ENV=development npm install
 
-	#echo "---> Building your Node application from source"
-	#npm install
+#do not fail when there is no build script
+echo "---> Building in production mode"
+npm run build --if-present
 
-#else
-	echo "-------------------------"
-	echo "- List repos"
-	cd /etc/yum.repos.d
-	ls -l
-	echo "-------------------------"
-	echo " "
-	cd /opt/app-root/src
+echo "---> Pruning the development dependencies"
+npm prune
 
-	echo "---> Installing all dependencies"
-	NODE_ENV=development npm install
-
-	#do not fail when there is no build script
-	echo "---> Building in production mode"
-	npm run build --if-present
-	
-	echo "---> Build done, one way or another"
-	ls -l
-
-	if [ -x "npm-debug.log" ]; then
-		echo "---> log"
-		cat ./npm-debug.log
-	fi
-
-	echo "---> Pruning the development dependencies"
-	npm prune
-
-	# Clear the npm's cache and tmp directories only if they are not a docker volumes
-	NPM_CACHE=$(npm config get cache)
-	if ! mountpoint $NPM_CACHE; then
-		echo "---> Cleaning the npm cache $NPM_CACHE"
-		npm cache clean
-	fi
-	NPM_TMP=$(npm config get tmp)
-	if ! mountpoint $NPM_TMP; then
-		echo "---> Cleaning the $NPM_TMP/npm-*"
-		rm -rf $NPM_TMP/npm-*
-	fi
-
-#fi
+# Clear the npm's cache and tmp directories only if they are not a docker volumes
+NPM_CACHE=$(npm config get cache)
+if ! mountpoint $NPM_CACHE; then
+	echo "---> Cleaning the npm cache $NPM_CACHE"
+	npm cache clean
+fi
+NPM_TMP=$(npm config get tmp)
+if ! mountpoint $NPM_TMP; then
+	echo "---> Cleaning the $NPM_TMP/npm-*"
+	rm -rf $NPM_TMP/npm-*
+fi
 
 # Fix source directory permissions
 fix-permissions ./
